### ISSUE TITLE
有适配的7.7 版本吗？

### ISSUE THREAD

**Issue by learnpythontheew** [KennFalcon/elasticsearch-analysis-hanlp#101]
如题，有适配的7.7 版本吗？

**Comment by alieismy** [comment]
你自己修改pom文件，
。。。
<properties>
        <elasticsearch.version>7.8.1</elasticsearch.version>
<hanlp.version>portable-1.7.8</hanlp.version>
。。。

然后mvn clean package

**Comment by asd1245dss** [comment]
> 你自己修改pom文件，
> 。。。
> 
> <elasticsearch.version>7.8.1</elasticsearch.version>
> <hanlp.version>portable-1.7.8</hanlp.version>
> 。。。
> 
> 然后mvn clean package

同问啊，你说的pom文件是哪个项目的。。。。这个项目不是用gradle吗 @alieismy

**Comment by KennFalcon** [comment]
已添加适配7.7.0版本，有需要请自行下载
