### ISSUE TITLE
能说说在 7.5.2 版本中移除 hanlp_crf 分词方式的用意吗？

### ISSUE THREAD

**Issue by Alistair-zhong** [KennFalcon/elasticsearch-analysis-hanlp#104]
Hi @KennFalcon ：

在使用 `7.5.2` 版本的插件中我发现 `hanlp_crf` 分词方式不再被支持，我比较好奇为什么要移除它，是出于什么考虑呢？

因为我在之前的版本中配合 hanlp 官方的 `1.7.5` 数据包使用 `hanlp_crf`，感觉还行，分词的粒度会更细一点。如 `不能` 会被分成 `不` 和 `能`，而不是单单的 `不能`,并且看 hanlp 的官方文档描述 `crf` 的方式准确度比感知机分词方式会略高一点（这一点从测试结果中倒看不出）。所以我看到本插件 `7.5.2` 版本中移除了 `crf` 分词方式的支持，是比较好奇的。但我相信你有自己的考虑，能简单说说吗？

Thx

**Comment by KennFalcon** [comment]
抱歉，是个人适配失误，因为之前用的是CRFSegment方式，HanLP在之前的版本提出了废弃，然后采用了新的CRFLexicalAnalyzer方式进行分词，这个我这几天适配后会重新会在7.5.2之后的方法适配，如果想在7.5.2（含7.5.2）之前的版本使用，请自行打包

**Comment by Alistair-zhong** [comment]
It's Ok
