### ISSUE TITLE
elasticsearch analysis hanlp not support Elasticsearch verion 7.14.1

### ISSUE THREAD

**Issue by chenzhigang9521** [KennFalcon/elasticsearch-analysis-hanlp#132]
Plugin [analysis-hanlp] was built for Elasticsearch version 7.10.2 but version 7.14.1 is running

**Comment by VVeaker** [comment]
解决方式一: 降低elasticsearch的版本为7.10.2
解决方式二:自行下载插件源码包,修改es版本为7.14.1后自行重新打包即可,修改版本及打包方式看首页文档说明

**Comment by VVeaker** [comment]
工程改为gradle方式部署，重新修改打包请使用./gradlew assemble命令，否则可能因本地gradle版本不匹配导致问题
github release增加MD5校验，若发现MD5值和release包计算得出的不一致，请勿使用，网盘会一直放在那。
部分版本因为工作原因可能无法及时更新，请自行打包（一般ES小版本迭代不会有大的改动，只需要更改版本号即可，版本号在gradle.properties中修改）

**Comment by chenzhigang9521** [comment]
> 

试了您说的方式，打包的时候会报错

**Comment by chenzhigang9521** [comment]
> > 
> 
> 试了您说的方式，打包的时候会报错

**Comment by chenzhigang9521** [comment]
> 工程改为gradle方式部署，重新修改打包请使用./gradlew assemble命令，否则可能因本地gradle版本不匹配导致问题 github release增加MD5校验，若发现MD5值和release包计算得出的不一致，请勿使用，网盘会一直放在那。 部分版本因为工作原因可能无法及时更新，请自行打包（一般ES小版本迭代不会有大的改动，只需要更改版本号即可，版本号在gradle.properties中修改）
![image](https://user-images.githubusercontent.com/25320051/176854013-3c19d4af-fa80-44a1-91f3-61f8a31aaf63.png)

**Comment by liweijian199011** [comment]
> 

es8用hanlp也可以用这种方式安装吗？
