### ISSUE TITLE
Unknown plugin 7.10.2（已解决，含linux上7.10.2完全安装指南）

### ISSUE THREAD

**Issue by EchoShoot** [KennFalcon/elasticsearch-analysis-hanlp#145]
# 问题已经解决
[安装教程看这里](https://github.com/KennFalcon/elasticsearch-analysis-hanlp/issues/145#issuecomment-1564217920)

# 版本是这个
{
"name": "k8s-node2",
"cluster_name": "elasticsearch",
"cluster_uuid": "-0KnoKGTRTOtb4NWGqURpw",
["version"](http://0.0.0.0:9200/): {
"number": "7.10.2",
"build_flavor": "default",
"build_type": "rpm",
"build_hash": "747e1cc71def077253878a59143c1f785afa92b9",
"build_date": "2021-01-13T00:42:12.435326Z",
"build_snapshot": false,
"lucene_version": "8.7.0",
"minimum_wire_compatibility_version": "6.8.0",
"minimum_index_compatibility_version": "6.0.0-beta1"
},
"tagline": "You Know, for Search"
}

# 解压也会报错
[root@k8s-node2 bin]# ./elasticsearch-plugin install /mnt/data3/xxx/hanlp/
-> Installing /mnt/data3/cuiyanhong/hanlp/
-> Failed installing /mnt/data3/cuiyanhong/hanlp/
-> Rolling back /mnt/data3/cuiyanhong/hanlp/
-> Rolled back /mnt/data3/cuiyanhong/hanlp/
A tool for managing installed elasticsearch plugins

Non-option arguments:
command              

Option             Description        
------             -----------        
-E <KeyValuePair>  Configure a setting
-h, --help         Show help          
-s, --silent       Show minimal output
-v, --verbose      Show verbose output
ERROR: Unknown plugin /mnt/data3/xxx/hanlp/

> 这个  /mnt/data3/xxx/hanlp/ 是 /mnt/mnt/data3/elasticsearch-analysis-hanlp-7.10.2.zip 解压后的文件

# 不解压也会报错
[root@k8s-node2 bin]# ./elasticsearch-plugin install /mnt/data3/elasticsearch-analysis-hanlp-7.10.2.zip 
-> Installing /mnt/data3/elasticsearch-analysis-hanlp-7.10.2.zip
-> Failed installing /mnt/data3/elasticsearch-analysis-hanlp-7.10.2.zip
-> Rolling back /mnt/data3/elasticsearch-analysis-hanlp-7.10.2.zip
-> Rolled back /mnt/data3/elasticsearch-analysis-hanlp-7.10.2.zip
A tool for managing installed elasticsearch plugins

Non-option arguments:
command              

Option             Description        
------             -----------        
-E <KeyValuePair>  Configure a setting
-h, --help         Show help          
-s, --silent       Show minimal output
-v, --verbose      Show verbose output
ERROR: Unknown plugin /mnt/data3/elasticsearch-analysis-hanlp-7.10.2.zip

**Comment by EchoShoot** [comment]
有没有什么办法手动安装， 复制文件都行？

**Comment by EchoShoot** [comment]
# 兄弟们还是得从 url 中下载才靠谱啊~ 不知道啥原理
[root@k8s-node2 bin]# ./elasticsearch-plugin install https://github.com/KennFalcon/elasticsearch-analysis-hanlp/releases/download/v7.10.2/elasticsearch-analysis-hanlp-7.10.2.zip
-> Installing https://github.com/KennFalcon/elasticsearch-analysis-hanlp/releases/download/v7.10.2/elasticsearch-analysis-hanlp-7.10.2.zip
-> Downloading https://github.com/KennFalcon/elasticsearch-analysis-hanlp/releases/download/v7.10.2/elasticsearch-analysis-hanlp-7.10.2.zip
[=================================================] 100%   
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.io.FilePermission plugins/analysis-hanlp/data/-#plus read,write,delete
* java.io.FilePermission plugins/analysis-hanlp/hanlp.cache#plus read,write,delete
* java.lang.RuntimePermission getClassLoader
* java.lang.RuntimePermission setContextClassLoader
* java.net.SocketPermission * connect,resolve
* java.util.PropertyPermission * read,write
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.

Continue with installation? [y/N]y

**Comment by EchoShoot** [comment]
# 安装后重启又报错(离了个大谱)
```
5月 26 18:43:08 k8s-node2 systemd-entrypoint[54593]:         ... 28 more
5月 26 18:43:08 k8s-node2 systemd-entrypoint[54593]:         at com.hankcs.hanlp.dictionary.CoreDictionary.<clinit>(CoreDictionary.java:44)
5月 26 18:43:08 k8s-node2 systemd-entrypoint[54593]: Caused by: java.lang.IllegalArgumentException: 核心词典/usr/share/elasticsearch/plugins/analysis-hanlp/data/dictionary/CoreNatureDictionary.mini.txt加载失败
5月 26 18:43:08 k8s-node2 systemd-entrypoint[54593]:         at java.base/java.lang.Thread.run(Thread.java:832)
5月 26 18:43:08 k8s-node2 systemd-entrypoint[54593]:         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
5月 26 18:43:08 k8s-node2 systemd-entrypoint[54593]:         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
5月 26 18:43:08 k8s-node2 systemd-entrypoint[54593]:         at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215)
5月 26 18:43:08 k8s-node2 systemd-entrypoint[54593]:         at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.>
5月 26 18:43:08 k8s-node2 systemd-entrypoint[54593]:         at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:684)
5月 26 18:43:08 k8s-node2 systemd-entrypoint[54593]:         at org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:162)
5月 26 18:43:08 k8s-node2 systemd-entrypoint[54593]:         at org.elasticsearch.cluster.service.ClusterApplierService.access$000(ClusterApplierService.java:68)
5月 26 18:43:08 k8s-node2 systemd-entrypoint[54593]:         at org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:418)
5月 26 18:43:08 k8s-node2 systemd-entrypoint[54593]:         at org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:471)
5月 26 18:43:08 k8s-node2 systemd-entrypoint[54593]:         at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:500)
5月 26 18:43:08 k8s-node2 systemd-entrypoint[54593]:         at org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:510)
5月 26 18:43:08 k8s-node2 systemd-entrypoint[54593]:         at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyClusterState(IndicesClusterStateService.java:246)
5月 26 18:43:08 k8s-node2 systemd-entrypoint[54593]:         at org.elasticsearch.indices.cluster.IndicesClusterStateService.createIndices(IndicesClusterStateService.java:486)
5月 26 18:43:08 k8s-node2 systemd-entrypoint[54593]:         at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:177)
5月 26 18:43:08 k8s-node2 systemd-entrypoint[54593]:         at org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:558)
5月 26 18:43:08 k8s-node2 systemd-entrypoint[54593]:         at org.elasticsearch.indices.IndicesService.createIndexService(IndicesService.java:655)
5月 26 18:43:08 k8s-node2 systemd-entrypoint[54593]:         at org.elasticsearch.index.IndexModule.newIndexService(IndexModule.java:438)
5月 26 18:43:08 k8s-node2 systemd-entrypoint[54593]:         at org.elasticsearch.index.analysis.AnalysisRegistry.build(AnalysisRegistry.java:218)
5月 26 18:43:08 k8s-node2 systemd-entrypoint[54593]:         at org.elasticsearch.index.analysis.AnalysisRegistry.build(AnalysisRegistry.java:531)
5月 26 18:43:08 k8s-node2 systemd-entrypoint[54593]:         at org.elasticsearch.index.analysis.AnalysisRegistry.produceAnalyzer(AnalysisRegistry.java:612)
5月 26 18:43:08 k8s-node2 systemd-entrypoint[54593]:         at org.elasticsearch.index.analysis.AnalysisRegistry.checkVersions(AnalysisRegistry.java:648)
5月 26 18:43:08 k8s-node2 systemd-entrypoint[54593]:         at org.apache.lucene.analysis.Analyzer.tokenStream(Analyzer.java:199)
5月 26 18:43:08 k8s-node2 systemd-entrypoint[54593]:         at org.apache.lucene.analysis.AnalyzerWrapper.createComponents(AnalyzerWrapper.java:136)
5月 26 18:43:08 k8s-node2 systemd-entrypoint[54593]:         at com.hankcs.lucene.HanLPSpeedAnalyzer.createComponents(HanLPSpeedAnalyzer.java:32)
5月 26 18:43:08 k8s-node2 systemd-entrypoint[54593]:         at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
5月 26 18:43:08 k8s-node2 systemd-entrypoint[54593]:         at com.hankcs.lucene.HanLPSpeedAnalyzer.lambda$createComponents$0(HanLPSpeedAnalyzer.java:33)
5月 26 18:43:08 k8s-node2 systemd-entrypoint[54593]:         at com.hankcs.hanlp.seg.Other.DoubleArrayTrieSegment.<init>(DoubleArrayTrieSegment.java:45)
5月 26 18:43:08 k8s-node2 systemd-entrypoint[54593]: java.lang.ExceptionInInitializerError
5月 26 18:43:08 k8s-node2 systemd-entrypoint[54593]: fatal error in thread [elasticsearch[k8s-node2][clusterApplierService#updateTask][T#1]], exiting

```

**Comment by EchoShoot** [comment]
[#612 ](https://github.com/hankcs/HanLP/issues/612)  提供了解决方案
chown -R elasticsearch /usr/share/elasticsearch/plugins/analysis-hanlp/
systemctl restart elasticsearch

**Comment by EchoShoot** [comment]
# ES 安装教程
## 下载安装
```shell
wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.16.3-x86_64.rpm 
sudo rpm --install elasticsearch-7.16.3-x86_64.rpm
```

## 启动密码安全
sudo vim /etc/elasticsearch/elasticsearch.yml 
```
http.cors.enabled: true 
http.cors.allow-origin: "*" 
http.cors.allow-headers: Authorization 
xpack.security.enabled: true 
xpack.security.transport.ssl.enabled: true
```

## 配置密码（根据提示去配置） 
```shell
/usr/share/elasticsearch/bin/elasticsearch-setup-passwords interactive
```

# 开放公网（配置完密码后） 
```shell
sudo vim /etc/elasticsearch/elasticsearch.yml 
network.host: 0.0.0.0 
discovery.seed_hosts: ["0.0.0.0"] 
http.port: 9200
```

# 重启 
```shell
sudo systemctl restart elasticsearch 
curl http://x.x.x.x:9200 # 验证一下
```

# 安装 hanlp 7.10.2
## 安装插件
```shell
sudo -i   # 提升到 root 账号
cd /usr/share/elasticsearch/bin
./elasticsearch-plugin install https://github.com/KennFalcon/elasticsearch-analysis-hanlp/releases/download/v7.10.2/elasticsearch-analysis-hanlp-7.10.2.zip
```
## 修改权限
```
sudo -i   # 提升到 root 账号
chown -R elasticsearch /usr/share/elasticsearch/plugins/analysis-hanlp/
systemctl restart elasticsearch
```
## 验证安装
```
浏览器访问 http://x.x.x.x:9200/_cat/plugins
我这里显示 k8s-node2 analysis-hanlp 7.10.2
```

**Comment by EchoShoot** [comment]
感谢大家

**Comment by bo5655** [comment]
安装hanlp插件后启动ES失败了
Job for elasticsearch.service failed because the control process exited with error code.
See "systemctl status elasticsearch.service" and "journalctl -xeu elasticsearch.service" for details.

执行systemctl status elasticsearch.service后提示如下

× elasticsearch.service - Elasticsearch
     Loaded: loaded (/lib/systemd/system/elasticsearch.service; disabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2024-03-14 17:09:48 CST; 5min ago
       Docs: https://www.elastic.co
    Process: 2345213 ExecStart=/usr/share/elasticsearch/bin/systemd-entrypoint -p ${PID_DIR}/elasticsearch.pid --quiet (code=exited, status=1/FAILU>
   Main PID: 2345213 (code=exited, status=1/FAILURE)
        CPU: 38.453s

Mar 14 17:09:48 iZ2vcdgpo69rodz9yc9qkoZ systemd-entrypoint[2345213]:         at java.base/java.lang.SecurityManager.checkRead(SecurityManager.java:>
Mar 14 17:09:48 iZ2vcdgpo69rodz9yc9qkoZ systemd-entrypoint[2345213]:         at java.base/java.io.File.isFile(File.java:880)
Mar 14 17:09:48 iZ2vcdgpo69rodz9yc9qkoZ systemd-entrypoint[2345213]:         at com.hankcs.hanlp.HanLP$Config.<clinit>(HanLP.java:335)
Mar 14 17:09:48 iZ2vcdgpo69rodz9yc9qkoZ systemd-entrypoint[2345213]:         ... 18 more
Mar 14 17:09:48 iZ2vcdgpo69rodz9yc9qkoZ systemd-entrypoint[2345460]: 2024-03-14 09:09:48,873969 UTC [2345460] INFO  Main.cc@103 Parent process died>
Mar 14 17:09:48 iZ2vcdgpo69rodz9yc9qkoZ systemd[1]: elasticsearch.service: Main process exited, code=exited, status=1/FAILURE
Mar 14 17:09:48 iZ2vcdgpo69rodz9yc9qkoZ systemd[1]: elasticsearch.service: Failed with result 'exit-code'.
Mar 14 17:09:48 iZ2vcdgpo69rodz9yc9qkoZ systemd[1]: elasticsearch.service: Unit process 2345460 (controller) remains running after unit stopped.
Mar 14 17:09:48 iZ2vcdgpo69rodz9yc9qkoZ systemd[1]: Failed to start Elasticsearch.
Mar 14 17:09:48 iZ2vcdgpo69rodz9yc9qkoZ systemd[1]: elasticsearch.service: Consumed 38.453s CPU time.

执行journalctl -xeu elasticsearch.service后提示如下：

░░ 
░░ The unit elasticsearch.service has entered the 'failed' state with result 'exit-code'.
Mar 14 17:09:48 iZ2vcdgpo69rodz9yc9qkoZ systemd[1]: elasticsearch.service: Unit process 2345460 (controller) remains running after unit stopped.
Mar 14 17:09:48 iZ2vcdgpo69rodz9yc9qkoZ systemd[1]: Failed to start Elasticsearch.
░░ Subject: A start job for unit elasticsearch.service has failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ A start job for unit elasticsearch.service has finished with a failure.
░░ 
░░ The job identifier is 46516 and the job result is failed.
Mar 14 17:09:48 iZ2vcdgpo69rodz9yc9qkoZ systemd[1]: elasticsearch.service: Consumed 38.453s CPU time.
░░ Subject: Resources consumed by unit runtime
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ The unit elasticsearch.service completed and consumed the indicated resources.
hanlp插件卸载，ES服务正常启动，请问大佬是什么原因呢，系统环境是Ubuntu 22.04.4 LTS
