### ISSUE TITLE
如何在分词时方便地开启归一化？

### ISSUE THREAD

**Issue by hapjin** [KennFalcon/elasticsearch-analysis-hanlp#15]
hi，KennFalcon：
我使用的插件版本： elasticsearch-analysis-hanlp for ElasticSearch6.3.2 
由于HanLP在分词的时候`HanLP.Config.Normalization=false`，默认是不开启Normalization。**但是我想在分词的时候，开启归一化操作。**
我采用的Analyzer是`com.hankcs.lucene.HanLPStandardAnalyzer`，目前我的做法是在`HanLPStandardAnalyzer.createComponents()`方法中添加了一行语句：
```java
    @Override
    protected Analyzer.TokenStreamComponents createComponents(String fieldName) {
        //分词时开启归一化
        AccessController.doPrivileged((PrivilegedAction) () -> HanLP.Config.Normalization = true);
        Tokenizer tokenizer = new HanLPTokenizer(HanLP.newSegment(), configuration);
        return new Analyzer.TokenStreamComponents(tokenizer);
    }
```
然后重新打jar包，复制到`elasticsearch-6.3.2/plugins/analysis-hanlp`目录下替换掉原来的jar，重启ES。
我的问题是：
是否考虑把 分词时开启归一化 做成可配置的方式？比如在 定义索引 指定 content字段的 analyzer 时，加一个Normalization 的配置选项：
```html
        "content": {
          "type": "text",
          "analyzer": "hanlp_standard",
          "normalization":true
```
或者在`com.hankcs.cfg.Configuration`里面添加一个类似于 `enableNormalization`的配置选项，做相应的归一化操作支持？
或者说，您有什么其他好的方法吗？

**Comment by KennFalcon** [comment]
好的，下一个版本我会考虑将这个配置开放出来

hapjin <notifications@github.com> 于2018年12月24日周一 上午10:21写道：

**Comment by hapjin** [comment]
谢谢。

**Comment by KennFalcon** [comment]
6.6.0、6.6.1版本支持了归一化，有需要可以看一下
