### ISSUE TITLE
请问enable_custom_dictionary这些配置要怎么设置？

### ISSUE THREAD

**Issue by jiqiujia** [KennFalcon/elasticsearch-analysis-hanlp#22]
I try to customize an analyzer like this, but it doesn't work
![image](https://user-images.githubusercontent.com/8109984/53927343-8540e800-40c1-11e9-84b7-2df76d5a7e37.png)

**Comment by KennFalcon** [comment]
`{
    "index" : {
        "analysis" : {
            "analyzer" : {
                "hanlp1" : {
                    "tokenizer" : "my_hanlp"
                    }
            },
            "tokenizer" : {
                "my_hanlp" : {
                    "type" : "hanlp",
                    "enable_index_mode" : true
                }
            }
        }
    }
}`

其中hanlp1，就是自定义的analyzer
