### ISSUE TITLE
Configuration里的配置如何设置

### ISSUE THREAD

**Issue by rainLeelzr** [KennFalcon/elasticsearch-analysis-hanlp#27]
我需要把enable_number_quantifier_recognize设置为true，请问这个配置，应该在什么时候，什么地方设置的？

**Comment by rainLeelzr** [comment]
{
    "index" : {
        "analysis" : {
            "analyzer" : {
                "hanlp1" : {
                    "tokenizer" : "my_hanlp"
                    }
            },
            "tokenizer" : {
                "my_hanlp" : {
                    "type" : "hanlp",
                    "enable_number_quantifier_recognize" : true
                }
            }
        }
    }
}

我这样创建索引，在HanLPAnalyzer里加了打印语句，打印出来的enable_number_quantifier_recognize还是false

**Comment by KennFalcon** [comment]
请问你是在哪里打印语句，具体的位置麻烦发一下

**Comment by rainLeelzr** [comment]
![image](https://user-images.githubusercontent.com/12439084/56105056-1894f500-5f6d-11e9-89ef-dbad53ac2ed9.png)

不好意思，因为在内网开发，只能拍照片给你了

**Comment by KennFalcon** [comment]
你可以在HanLPTokenizer，这边查看这个变量值
```
@Override
final public boolean incrementToken() throws IOException {
      logger.info("isEnableNumberQuantifierRecognize: {}", configuration.isEnableNumberQuantifierRecognize());
      clearAttributes();
      ...
}
```
