### ISSUE TITLE
CustomDictionary线程安全吗

### ISSUE THREAD

**Issue by rainLeelzr** [KennFalcon/elasticsearch-analysis-hanlp#28]
CustomDictionary.remove(String)
CustomDictionary.insert(String, String)
请问这2个方法，线程安全吗？

我们有一个场景：远程词典删除了一行词，已加载的词典也需要删除这行词。
现在远程词典的加载逻辑，只是不断增加远程词典的词条，而不会删除远程词典被删除的词条。

我修改了一下RemoteMonitor加载远程词典的方法，使其能与上次已加载的远程词典对比，从而计算出需要删除的词条。

有一个远程词典，100w行数据，业务会不断优化词典，所以这2个方法，会经常调用。如果我用集合的并行流paralleStream()来并执行CustomDictionary.insert，会不会有问题？

**Comment by KennFalcon** [comment]
该方法是Hanlp的自定义词典插入方法，得具体看看源码，目前看是非线程安全的，建议还是不要采用这种方式，100w的数据，建议还是不要用远程方式做，如果能固化的词，尽量还是采用文本方式存储加载，对hanlp这部分的代码有疑问的话可以看：[https://github.com/hankcs/HanLP](url)
