### ISSUE TITLE
hanlp_index的tokenizer没有效果，analyzer有效果

### ISSUE THREAD

**Issue by BearKid** [KennFalcon/elasticsearch-analysis-hanlp#30]
我最开始的需求是希望自定义一个能够剔除html标签的hanlp_index的analyzer, 但使用时发现没了多粒度分词的效果。
> {
	"analysis": {
		"analyzer": {
			"default": {
				"filter": [
					"lowercase",
					"asciifolding"
				],
				"char_filter": [
					"html_strip"
				],
				"type": "custom",
				"tokenizer": "hanlp_index"
			}
		}
	}
}
`

**于是我用_analyze分析，从结果看似乎是hanlp_index的tokenizer有问题。**
**hanlp_index的analyzer可以多粒度分词**
`
GET _analyze
{
  "text": ["<p>除甲醛</p>", "汽车座椅"],
  "analyzer": "hanlp_index"
}
`
**结果**
{
  "tokens" : [
    {
      "token" : "&lt;p&gt;",
      "start_offset" : 0,
      "end_offset" : 3,
      "type" : "nx",
      "position" : 0
    },
    {
      "token" : "除甲醛",
      "start_offset" : 6,
      "end_offset" : 9,
      "type" : "n",
      "position" : 1
    },
    {
      "token" : "甲醛",
      "start_offset" : 10,
      "end_offset" : 12,
      "type" : "n",
      "position" : 2
    },
    {
      "token" : "&lt;",
      "start_offset" : 14,
      "end_offset" : 15,
      "type" : "nx",
      "position" : 3
    },
    {
      "token" : "/",
      "start_offset" : 16,
      "end_offset" : 17,
      "type" : "w",
      "position" : 4
    },
    {
      "token" : "p&gt;",
      "start_offset" : 18,
      "end_offset" : 20,
      "type" : "nx",
      "position" : 5
    },
    {
      "token" : "汽车座椅",
      "start_offset" : 24,
      "end_offset" : 28,
      "type" : "nz",
      "position" : 6
    },
    {
      "token" : "汽车",
      "start_offset" : 28,
      "end_offset" : 30,
      "type" : "n",
      "position" : 7
    },
    {
      "token" : "车座",
      "start_offset" : 31,
      "end_offset" : 33,
      "type" : "n",
      "position" : 8
    },
    {
      "token" : "座椅",
      "start_offset" : 34,
      "end_offset" : 36,
      "type" : "n",
      "position" : 9
    }
  ]
}

**hanlp_index的tokenizer的没有多粒度分词效果**
`GET /_analyze
{
  "text": ["<p>除甲醛</p>","汽车座椅"],
  "tokenizer": "hanlp_index"
}`

**结果**
 {
  "tokens" : [
    {
      "token" : "&lt;p&gt;",
      "start_offset" : 0,
      "end_offset" : 3,
      "type" : "nx",
      "position" : 0
    },
    {
      "token" : "除甲醛",
      "start_offset" : 3,
      "end_offset" : 6,
      "type" : "n",
      "position" : 1
    },
    {
      "token" : "<",
      "start_offset" : 6,
      "end_offset" : 7,
      "type" : "nx",
      "position" : 2
    },
    {
      "token" : "/",
      "start_offset" : 7,
      "end_offset" : 8,
      "type" : "w",
      "position" : 3
    },
    {
      "token" : "p>",
      "start_offset" : 8,
      "end_offset" : 10,
      "type" : "nx",
      "position" : 4
    },
    {
      "token" : "汽车座椅",
      "start_offset" : 22,
      "end_offset" : 26,
      "type" : "nz",
      "position" : 5
    }
  ]
}

**Comment by BearKid** [comment]
看了源码，发现是bug，HanLPTokenizerFactory里创建Index Tokenizer时只为configuration设置了enableIndexMode，但是关键的Segment并没有开启enableIndexMode。
看到目前有个新的pull request能顺带修复这个问题：#29 ，但我不是很赞同在HanLPTokenizer构造器里对segment进行设置，应该由HanLPTokenizerFactory工厂负责准备好HanLPTokenizer需要的东西。

**Comment by KennFalcon** [comment]
好的，这块我会确认一下

**Comment by KennFalcon** [comment]
抱歉，这个的确是个重大的bug，我会修复过来，并提供近几个对应版本下载方式

**Comment by KennFalcon** [comment]
已在最近的几个版本修复这个问题，最新包在百度盘：
链接:https://pan.baidu.com/s/1mFPNJXgiTPzZeqEjH_zifw  密码:i0o7
