### ISSUE TITLE
6.3.2版本报错index_not_found_exception

### ISSUE THREAD

**Issue by zhengchao88** [KennFalcon/elasticsearch-analysis-hanlp#31]
使用elasticsearch-plugin install的方式安装的，运行之后报下面的错误：
curl 'https://$ES_URL:9200/twitter2/_analyze?pretty=true' -H 'Content-Type: application/json' -d '{ "tokenizer":"hanlp", "text":"士大夫敢死队风格"}'
{
  "error" : {
    "root_cause" : [
      {
        "type" : "index_not_found_exception",
        "reason" : "no such index",
        "resource.type" : "index_expression",
        "resource.id" : "twitter2",
        "index_uuid" : "_na_",
        "index" : "twitter2"
      }
    ],
    "type" : "index_not_found_exception",
    "reason" : "no such index",
    "resource.type" : "index_expression",
    "resource.id" : "twitter2",
    "index_uuid" : "_na_",
    "index" : "twitter2"
  },
  "status" : 404
}

hanlp.properties文件是在ES_PATH/config/analysis-hanlp/下。

**Comment by KennFalcon** [comment]
这是索引不存在的错误，需要先创建twitter2索引

**Comment by KennFalcon** [comment]
该issue我暂时关了，如果有其他疑问，请重开issue
