### ISSUE TITLE
V7.0.0配置hanlp-remote.xml中remote_ext_dict远程分词地址无效，而同样的配置在ik就有效

### ISSUE THREAD

**Issue by bonjs** [KennFalcon/elasticsearch-analysis-hanlp#34]
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE properties SYSTEM "http://java.sun.com/dtd/properties.dtd">
<properties>
    <comment>HanLP Analyzer 扩展配置</comment>

    
    <entry key="remote_ext_dict">http://我的地址:1888/a.txt</entry>

    
    
</properties>

http://我的地址:1888/a.txt 内容
中
华

POST _analyze
{
  "text": "中华人民共和国",
  "tokenizer": "hanlp_index"
}

结果：
{
  "tokens" : [
    {
      "token" : "中华人民共和国",
      "start_offset" : 0,
      "end_offset" : 7,
      "type" : "ns",
      "position" : 0
    },
    {
      "token" : "中华人民",
      "start_offset" : 0,
      "end_offset" : 4,
      "type" : "nz",
      "position" : 1
    },
    {
      "token" : "中华",
      "start_offset" : 0,
      "end_offset" : 2,
      "type" : "nz",
      "position" : 2
    },
    {
      "token" : "华人",
      "start_offset" : 1,
      "end_offset" : 3,
      "type" : "n",
      "position" : 3
    },
    {
      "token" : "人民共和国",
      "start_offset" : 2,
      "end_offset" : 7,
      "type" : "nz",
      "position" : 4
    },
    {
      "token" : "人民",
      "start_offset" : 2,
      "end_offset" : 4,
      "type" : "n",
      "position" : 5
    },
    {
      "token" : "共和国",
      "start_offset" : 4,
      "end_offset" : 7,
      "type" : "n",
      "position" : 6
    },
    {
      "token" : "共和",
      "start_offset" : 4,
      "end_offset" : 6,
      "type" : "n",
      "position" : 7
    }
  ]
}

期望结果中出现单“中”，“华”的记录

**Comment by KennFalcon** [comment]
HanLP index分词模式，默认分词颗粒度为2，所以不会分出“中”，“华”的记录

**Comment by bonjs** [comment]
多谢回复。
那这个默认分词颗粒度可以修改吗？

**Comment by KennFalcon** [comment]
目前分词插件没有提供出来，后续会增加

**Comment by shguan2018** [comment]
这个我也发现远程地址无效,我跟踪了源代码,发现在这个地方有问题  
com.hankcs.dic.RemoteMonitor  中的 

public void run() {
        SpecialPermission.check();
        AccessController.doPrivileged((PrivilegedAction<Void>) () -> {
            runUnprivileged();
            return null;
        });
    }

SpecialPermission.check()  这个地方不执行了， 是权限设置有问题吗？

**Comment by KennFalcon** [comment]
好的  我这边再测试一下

**Comment by KennFalcon** [comment]
我测试了一下应该没什么问题，如下：

```
POST _analyze
{
"text": "太古绘卷是一款国产游戏",
"tokenizer": "hanlp"
}
```

未设置远程词典时：

```
{
  "tokens" : [
    {
      "token" : "太古",
      "start_offset" : 0,
      "end_offset" : 2,
      "type" : "nz",
      "position" : 0
    },
    {
      "token" : "绘卷",
      "start_offset" : 2,
      "end_offset" : 4,
      "type" : "nz",
      "position" : 1
    },
    {
      "token" : "是",
      "start_offset" : 4,
      "end_offset" : 5,
      "type" : "vshi",
      "position" : 2
    },
    {
      "token" : "一",
      "start_offset" : 5,
      "end_offset" : 6,
      "type" : "m",
      "position" : 3
    },
    {
      "token" : "款",
      "start_offset" : 6,
      "end_offset" : 7,
      "type" : "q",
      "position" : 4
    },
    {
      "token" : "国产",
      "start_offset" : 7,
      "end_offset" : 9,
      "type" : "b",
      "position" : 5
    },
    {
      "token" : "游戏",
      "start_offset" : 9,
      "end_offset" : 11,
      "type" : "n",
      "position" : 6
    }
  ]
}
```

远程词典配置词如下：
```
"太古绘卷"
```

配置远程词典后结果为：
```
{
  "tokens" : [
    {
      "token" : "太古绘卷",
      "start_offset" : 0,
      "end_offset" : 4,
      "type" : "n",
      "position" : 0
    },
    {
      "token" : "是",
      "start_offset" : 4,
      "end_offset" : 5,
      "type" : "vshi",
      "position" : 1
    },
    {
      "token" : "一",
      "start_offset" : 5,
      "end_offset" : 6,
      "type" : "m",
      "position" : 2
    },
    {
      "token" : "款",
      "start_offset" : 6,
      "end_offset" : 7,
      "type" : "q",
      "position" : 3
    },
    {
      "token" : "国产",
      "start_offset" : 7,
      "end_offset" : 9,
      "type" : "b",
      "position" : 4
    },
    {
      "token" : "游戏",
      "start_offset" : 9,
      "end_offset" : 11,
      "type" : "n",
      "position" : 5
    }
  ]
}
```

如果还有其他问题，请重开issue

**Comment by shguan2018** [comment]
remote_ext_stopwords   这个停用词经过测试发现无效,设置了停用词，但没有用处，索引库里还是有停用词存在

**Comment by wjyunn** [comment]
hanlp-remote.xml文件中配置了远程词典以及停用词词典，但是都没有生效，也没有错误日志
<entry key="remote_ext_dict">http://xxx/userWords</entry>
<entry key="remote_ext_stopwords">http://xxx/stopWords</entry>
路径返回的是流
userWords中是
太古里  n       1000
stopWords中是
准备
测试
使用kibana验证
POST _analyze
{
  "text": "准备相应文件",
  "tokenizer": "hanlp"
}
返回
{
  "tokens" : [
    {
      "token" : "准备",
      "start_offset" : 0,
      "end_offset" : 2,
      "type" : "n",
      "position" : 0
    },
    {
      "token" : "相应",
      "start_offset" : 2,
      "end_offset" : 4,
      "type" : "vi",
      "position" : 1
    },
    {
      "token" : "文件",
      "start_offset" : 4,
      "end_offset" : 6,
      "type" : "n",
      "position" : 2
    }
  ]
}

POST _analyze
{
  "text": "太古里门店",
  "tokenizer": "hanlp"
}
返回
{
  "tokens" : [
    {
      "token" : "太古",
      "start_offset" : 0,
      "end_offset" : 2,
      "type" : "nz",
      "position" : 0
    },
    {
      "token" : "里",
      "start_offset" : 2,
      "end_offset" : 3,
      "type" : "f",
      "position" : 1
    },
    {
      "token" : "门店",
      "start_offset" : 3,
      "end_offset" : 5,
      "type" : "n",
      "position" : 2
    }
  ]
}
验证最终远程词典没有生效
