### ISSUE TITLE
请问支持ES 5.6.4吗？

### ISSUE THREAD

**Issue by JackGzj** [KennFalcon/elasticsearch-analysis-hanlp#40]
请问支持ES 5.6.4吗？

**Comment by KennFalcon** [comment]
这个可能需要重新适配，需要一定的修改，因为有些接口在5.x不太一样，如果需要可以自行做些适配，大体的框架基本相同

**Comment by KennFalcon** [comment]
ES最新版本还是做了很多的优化，如果第一次使用ES，建议还是使用比较新的版本

**Comment by JackGzj** [comment]
> ES最新版本还是做了很多的优化，如果第一次使用ES，建议还是使用比较新的版本

好的，谢谢你的回复。因为这边项目用了5.6.4，不太好直接升级。

**Comment by KennFalcon** [comment]
后面会将最近几次的优化merge到5.x分支，好了会通知

**Comment by KennFalcon** [comment]
已将最近的几次优化，bug修复merge到了5.x分支（测试基于5.6.14），如果有需要，请自行修改版本号重新打包

**Comment by KennFalcon** [comment]
该issue我暂时关了，如果有其他疑问，请重开issue
