### ISSUE TITLE
从官网下载Model 放入网站后 奔溃

### ISSUE THREAD

**Issue by q2434006** [KennFalcon/elasticsearch-analysis-hanlp#41]
您好，在使用您的框架的过程中出现了一个问题，不知道是否使用错误。
从hanlp官网下载model数据后放入 /plugins/analysis-hanlp/data/model 下，重启 ES，
使用 _analyze 测试分词正常。
  "hanLPAnalyzer" : {
              "type" : "custom",
              "char_filter" : [
                "charconvert"
              ],
              "tokenizer" : "hanlp_nlp_word"
            },
        "hanlp_nlp_word" : {
              "enable_normalization" : "true",
              "enable_remote_dict" : "true",
              "type" : "hanlp_nlp"
            }
然后使用 _search 查询数据，如下，数据大约为200W条，查询耗时超过2S，持续点击5次以上，出现401错误，后台日志提示内存溢出.
POST /poi/_search
{
	"from": 0,
	"size": 10,
	"query": {
		"dis_max": {
			"tie_breaker": 0.3,
			"queries": [{
				"match": {
					"full_q": {
						"query": "青年路",
						"operator": "OR",
						"analyzer": "hanLPAnalyzer"
					}
				}
			}],
			"boost": 1.0
		}
	},
	"post_filter": {
		"bool": {
			"adjust_pure_negative": true,
			"boost": 1.0
		}
	}
}

**Comment by KennFalcon** [comment]
具体的报错信息和详细操作步骤麻烦贴一下

**Comment by q2434006** [comment]
错误信息如下：
![1565073980(1)](https://user-images.githubusercontent.com/12470760/62516977-fd6e2e00-b858-11e9-94cd-8100ee2e4d93.png)

**Comment by KennFalcon** [comment]
ES内存设置的是多少G

**Comment by KennFalcon** [comment]
该issue我暂时关了，如果有其他疑问，请重开issue
