### ISSUE TITLE
怎么从新打包，修复我的老版本的问题？具体改怎么操作？

### ISSUE THREAD

**Issue by vincent775** [KennFalcon/elasticsearch-analysis-hanlp#42]
https://github.com/KennFalcon/elasticsearch-analysis-hanlp/issues/24

我也遇到的以上的问题，不过我的版本为6.4.

**Comment by KennFalcon** [comment]
我将最新的更新merge到了6.x分支，你可以自行打包一下，在pom文件中修改版本号后重新打包即可

**Comment by vincent775** [comment]
测试之后没问题，谢谢。

**Comment by KennFalcon** [comment]
指的是自定义词典吗，如果是的话，目前提供了两种方式，可以看README，里面有介绍，如果是CRF或者NLP模型，请看一下HanLP那边的介绍

**Comment by KennFalcon** [comment]
我先关掉issue了，如果有其他问题请重开issue
