### ISSUE TITLE
search_analyzer无法设置为hanlp_nlp，设置为hanlp可以成功 

### ISSUE THREAD

**Issue by zhengyangyong** [KennFalcon/elasticsearch-analysis-hanlp#45]
ref : https://github.com/KennFalcon/elasticsearch-analysis-hanlp/issues/38
https://github.com/KennFalcon/elasticsearch-analysis-hanlp/pull/35

最新代码测试了，看起来并没有解决：
设置search_analyzer为hanlp_nlp

{
    "properties": {
        "content": {
            "type": "text",
            "analyzer": "hanlp_nlp",
            "search_analyzer": "hanlp_nlp"
        },
        "remark": {
            "type": "text",
            "analyzer": "hanlp_nlp",
            "search_analyzer": "hanlp_nlp"
        }
    }
}

![image](https://user-images.githubusercontent.com/374335/63663019-52b3b480-c7f3-11e9-8314-b627d2793854.png)

失败

设置为hanlp

{
    "properties": {
        "content": {
            "type": "text",
            "analyzer": "hanlp_nlp",
            "search_analyzer": "hanlp"
        },
        "remark": {
            "type": "text",
            "analyzer": "hanlp_nlp",
            "search_analyzer": "hanlp"
        }
    }
}

![image](https://user-images.githubusercontent.com/374335/63663084-8a226100-c7f3-11e9-8b17-c5a7e74e2cbd.png)

没问题！

**Comment by KennFalcon** [comment]
ES的报错信息有吗？

**Comment by KennFalcon** [comment]
好的  我再看一下  看来单独设置search有问题

**Comment by KennFalcon** [comment]
我看了一下，这个是ES的机制，如果你analyzer和search_analyzer设置是一样的话，获取mapping信息就是一样，search_analyzer是不会显示出来的，我用hanlp也测试了一下：
```
PUT test
{
  "mappings": {
    "properties": {
      "content": {
        "type": "text",
        "analyzer": "hanlp",
        "search_analyzer": "hanlp"
      },
      "remark": {
        "type": "text",
        "analyzer": "hanlp",
        "search_analyzer": "hanlp"
      }
    }
  }
}
```
获取Mapping
```
{
  "test" : {
    "mappings" : {
      "properties" : {
        "content" : {
          "type" : "text",
          "analyzer" : "hanlp"
        },
        "remark" : {
          "type" : "text",
          "analyzer" : "hanlp"
        }
      }
    }
  }
}
```
如果你设置不一样，比如我将你上面的例子改为，analyzer设置为hanlp，search_analyzer设置为hanlp_nlp，这样就会显示出来
```
PUT test1
{
  "mappings": {
    "properties": {
      "content": {
        "type": "text",
        "analyzer": "hanlp",
        "search_analyzer": "hanlp_nlp"
      },
      "remark": {
        "type": "text",
        "analyzer": "hanlp",
        "search_analyzer": "hanlp_nlp"
      }
    }
  }
}
```
获取mapping
```
{
  "test1" : {
    "mappings" : {
      "properties" : {
        "content" : {
          "type" : "text",
          "analyzer" : "hanlp",
          "search_analyzer" : "hanlp_nlp"
        },
        "remark" : {
          "type" : "text",
          "analyzer" : "hanlp",
          "search_analyzer" : "hanlp_nlp"
        }
      }
    }
  }
}
```

**Comment by KennFalcon** [comment]
ES如果你单独设置search_analyzer的话，默认就会采用analyzer设置的分词器，所以如果你两者都是一样的话，不需要单独设置，或者你可以采用查询时设置分词器的方式进行不同分词方式的查询

**Comment by zhengyangyong** [comment]
OK
