### ISSUE TITLE
请问远程词典能设置定时任务时间吗？

### ISSUE THREAD

**Issue by kidcrb** [KennFalcon/elasticsearch-analysis-hanlp#46]
现在每分钟调用一次远程词典，这个时间定时任务能设置吗？

**Comment by KennFalcon** [comment]
如果有这方面的需求，请重新修改代码打包，代码在com.hankcs.dic.Dictionary
![image](https://user-images.githubusercontent.com/10258209/63925888-7558fe00-ca7d-11e9-9e3f-7b60703d0a2a.png)

**Comment by kidcrb** [comment]
> 如果有这方面的需求，请重新修改代码打包，代码在com.hankcs.dic.Dictionary
> ![image](https://user-images.githubusercontent.com/10258209/63925888-7558fe00-ca7d-11e9-9e3f-7b60703d0a2a.png)

好的，谢谢
