### ISSUE TITLE
动态删除词条

### ISSUE THREAD

**Issue by Dongzai1005** [KennFalcon/elasticsearch-analysis-hanlp#47]
hi, ES版本7.2.0，如何能动态删除词条？
目前测试远程词库可以动态添加，但是删除词条后，ES没有删除，需要重启才生效
删除hanlp.cache和.bin文件都没有生效

源码是直接insert的词条，不知道是否提供了删除词条方法？

**Comment by KennFalcon** [comment]
是的  目前删除词条可能比较麻烦，这块会继续跟进，看看怎么删除比较合适
