### ISSUE TITLE
远处字典更新问题

### ISSUE THREAD

**Issue by zhaohailong** [KennFalcon/elasticsearch-analysis-hanlp#5]
IK可以配置热更新字典

从远处服务下载.dic文件，根据响应头的ETag判断是否需要进行字典数据替换，

希望hanlp也能实现

**Comment by KennFalcon** [comment]
Hanlp重新构建自定义词典速度比较慢，正在逐步先解决这个问题，后面会增加远端服务更新

**Comment by KennFalcon** [comment]
远程词典更新已经支持，可以试用一下，借鉴的IK分词器的方式，目前支持的版本>=6.5.2，如果需要低版本的，可以自行重新编译解决
