### ISSUE TITLE
enable_traditional_chinese_mode字典檔案內容也需要改為繁中嗎?

### ISSUE THREAD

**Issue by zxc654951** [KennFalcon/elasticsearch-analysis-hanlp#53]
您好，已經設置繁中
`PUT test
{
  "settings": {
    "analysis": {
      "analyzer": {
        "tc_hanlp": {
          "tokenizer": "hanlp"
        }
      },
      "tokenizer": {
        "tc_hanlp": {
          "type": "hanlp",
          "enable_traditional_chinese_mode": true,
          "enable_custom_config": true
        }
      }
    }
  }
}`
但打印結果似乎只能分詞簡中，是否須將字典檔內容改為繁中?
`POST test/_analyze
{
  "text": "美國阿拉斯加州發生8.0級地震",
  "analyzer": "tc_hanlp"
}`

`{
  "tokens" : [
    {
      "token" : "美",
      "start_offset" : 0,
      "end_offset" : 1,
      "type" : "b",
      "position" : 0
    },
    {
      "token" : "國",
      "start_offset" : 0,
      "end_offset" : 1,
      "type" : "w",
      "position" : 1
    },
    {
      "token" : "阿拉斯加州",
      "start_offset" : 0,
      "end_offset" : 5,
      "type" : "nsf",
      "position" : 2
    },
    {
      "token" : "發",
      "start_offset" : 0,
      "end_offset" : 1,
      "type" : "n",
      "position" : 3
    },
    {
      "token" : "生",
      "start_offset" : 0,
      "end_offset" : 1,
      "type" : "v",
      "position" : 4
    },
    {
      "token" : "8.0",
      "start_offset" : 0,
      "end_offset" : 3,
      "type" : "m",
      "position" : 5
    },
    {
      "token" : "級",
      "start_offset" : 0,
      "end_offset" : 1,
      "type" : "n",
      "position" : 6
    },
    {
      "token" : "地震",
      "start_offset" : 0,
      "end_offset" : 2,
      "type" : "n",
      "position" : 7
    }
  ]
}`

**Comment by KennFalcon** [comment]
好的   我测试研究一下

**Comment by zxc654951** [comment]
感謝您

**Comment by KennFalcon** [comment]
抱歉，最近公司比较忙，所以没有及时回复，你这个是设置错误了，正确的设置如下：
```
PUT test
{
  "settings": {
    "analysis": {
      "analyzer": {
        "tc_hanlp": {
          "tokenizer": "tc_hanlp"
        }
      },
      "tokenizer": {
        "tc_hanlp": {
          "type": "hanlp",
          "enable_traditional_chinese_mode": true,
          "enable_custom_config": true
        }
      }
    }
  }
}
```

**Comment by KennFalcon** [comment]
tokenizer你要设置你新设置的tokenizer，不能用hanlp，不然就没用了
