### ISSUE TITLE
针对 ElasticSearch 6.8.x版本的插件没有打包发布的原因是？

### ISSUE THREAD

**Issue by hapjin** [KennFalcon/elasticsearch-analysis-hanlp#62]
hi, KennFalcon：
我目前的ES版本是6.3.2，安装的elasticsearch-analysis-hanlp插件版本也是6.3.2。我想升级一下ES到6.8版本，但是发现您并没有提供相应的6.8.x版本的elasticsearch-analysis-hanlp插件。
有点奇怪，是因为兼容性问题吗？还是？

PS：[ES官方文档](https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-upgrade.html) 中提到低版本的ES要想升级到7.x，必须先得升级到ES 6.8

**Comment by KennFalcon** [comment]
这个是因为6.8.x分支是在7.x版本之后才有的，你可以下载插件6.x分支的代码，修改版本号自行打包

**Comment by hapjin** [comment]
原来如此。已经搞定了，感谢答复。
