### ISSUE TITLE
设置index开启自定义配置时  出现高亮错位问题

### ISSUE THREAD

**Issue by williamcaptain** [KennFalcon/elasticsearch-analysis-hanlp#64]
PUT search_shop1
{
   "settings": {
    "analysis": {
      "analyzer": {
        "my_hanlp_analyzer": {
          "tokenizer": "my_hanlp",
                    "filter":
                        "lowercase"
        }
      },
      "tokenizer": {
        "my_hanlp": {
          "type": "hanlp_index",
          "enable_stop_dictionary": true,
          "enable_custom_dictionary":true,
          "enable_remote_dict":true,
          "enable_index_mode":true,
          "enable_custom_config": true

        }
      }
    }
  },
  "mappings": {
        "electroncomponent1":{
            "dynamic":"true",
            "properties":{
        
                "goodsName":{
                    "type":"text",
                    "analyzer":"my_hanlp_analyzer"
                },
                
              
                "brandName":{
                    "type":"text",
                    "analyzer":"my_hanlp_analyzer",
                    "fields": {
                    "keyword": {
              "type":     "keyword"
            }
          }
        },
            "factoryCode": {
          "type": "text",
          "analyzer": "my_hanlp_analyzer"
        }
        }
      }
    }
}

![image](https://user-images.githubusercontent.com/25821871/69948024-d20aff80-1529-11ea-94e6-b391266e4bc7.png)

**Comment by KennFalcon** [comment]
麻烦提供一下插件版本号以及ES版本号

**Comment by williamcaptain** [comment]
es 6.54版本 插件也是6.54




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "KennFalcon"<notifications@github.com&gt;; 
发送时间: 2019年12月3日(星期二) 上午9:43
收件人: "KennFalcon/elasticsearch-analysis-hanlp"<elasticsearch-analysis-hanlp@noreply.github.com&gt;; 
抄送: "当我遇见你"<269519441@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [KennFalcon/elasticsearch-analysis-hanlp] 设置index开启自定义配置时  出现高亮错位问题 (#64)




麻烦提供一下插件版本号以及ES版本号

**Comment by KennFalcon** [comment]
插件是你重新打包的吗？原来的版本上传的release包有点问题，offset有些bug，需要自行重新打包安装。你可以下载6.x分支的代码，修改pom中的版本号，然后自行打包安装。以下是我用7.4.2版本测试的结果：

创建索引：
```
PUT search_shop1
{
  "settings": {
    "analysis": {
      "analyzer": {
        "my_hanlp_analyzer": {
          "tokenizer": "my_hanlp",
          "filter": "lowercase"
        }
      },
      "tokenizer": {
        "my_hanlp": {
          "type": "hanlp_index",
          "enable_stop_dictionary": true,
          "enable_custom_dictionary": true,
          "enable_remote_dict": true,
          "enable_index_mode": true,
          "enable_custom_config": true
        }
      }
    }
  },
  "mappings": {
    "properties": {
      "goodsName": {
        "type": "text",
        "analyzer": "my_hanlp_analyzer"
      },
      "brandName": {
        "type": "text",
        "analyzer": "my_hanlp_analyzer",
        "fields": {
          "keyword": {
            "type": "keyword"
          }
        }
      },
      "factoryCode": {
        "type": "text",
        "analyzer": "my_hanlp_analyzer"
      }
    }
  }
}
```

插入数据：
```
POST search_shop1/_doc/1
{
  "goodsName": "贴片电容，100nf（104）±10% 50V",
  "factoryCode": "SDCL0603Q2N2ST02B03"
}
```

检索：
```
POST search_shop1/_search
{
  "query": {
    "bool": {
      "must": [
        {
          "multi_match": {
            "query": " %10",
            "fields": ["factoryCode", "goodsName"],
            "type": "cross_fields",
            "operator": "and"
          }
        }
      ]
    }
  },
  "highlight": {
    "fields": {
      "goodsName": {}
    }
  }
}
```

结果：
```
{
  "took" : 7,
  "timed_out" : false,
  "_shards" : {
    "total" : 1,
    "successful" : 1,
    "skipped" : 0,
    "failed" : 0
  },
  "hits" : {
    "total" : {
      "value" : 1,
      "relation" : "eq"
    },
    "max_score" : 0.5753642,
    "hits" : [
      {
        "_index" : "search_shop1",
        "_type" : "_doc",
        "_id" : "1",
        "_score" : 0.5753642,
        "_source" : {
          "goodsName" : "贴片电容，100nf（104）±10% 50V",
          "factoryCode" : "SDCL0603Q2N2ST02B03"
        },
        "highlight" : {
          "goodsName" : [
            "贴片电容，100nf（104）±<em>10</em><em>%</em> 50V"
          ]
        }
      }
    ]
  }
}
```

**Comment by KennFalcon** [comment]
如高亮使用还有问题，请重开issue
