### ISSUE TITLE
elasticsearch7.5.0 安装时提示Unknown plugin

### ISSUE THREAD

**Issue by liangzhiming** [KennFalcon/elasticsearch-analysis-hanlp#67]
我安装最新的ES7.5.0， 没有hanlp对应的版本，安装elasticsearch-analysis-hanlp-7.4.2.zip 提示
Unknown plugin elasticsearch-analysis-hanlp-7.4.2.zip

**Comment by KennFalcon** [comment]
最新适配7.5.0版本的插件已发布，请自行安装，issue我关掉了，如有其他问题请重开

**Comment by beijingzhangwei** [comment]
[elastic@ES-HANPL bin]$ ./elasticsearch-plugin install /home/elastic/elasticsearch-analysis-hanlp-7.5.1.zip
A tool for managing installed elasticsearch plugins

Non-option arguments:
command

Option         Description
------         -----------
-h, --help     show help
-s, --silent   show minimal output
-v, --verbose  show verbose output
ERROR: Unknown plugin /home/elastic/elasticsearch-analysis-hanlp-7.5.1.zip
