### ISSUE TITLE
查询时空格问题

### ISSUE THREAD

**Issue by zhaohailong** [KennFalcon/elasticsearch-analysis-hanlp#7]
分词时，空值建了索引

**Comment by KennFalcon** [comment]
HanLP默认分词器是都不会开过滤停止词的，所以在新的插件代码中，我加入了过滤停止词的方法，可以拉一下最新的看看，新的对应release是6.3.2，如果需要低版本的话，可自行编译打包。设置开启停止词等方法如下：
**首先设置索引分词器**
```
PUT test/
{
    "index" : {
        "analysis" : {
            "analyzer" : {
                "my_hanlp_analyzer" : {
                    "tokenizer" : "my_hanlp"
                    }
            },
            "tokenizer" : {
                "my_hanlp" : {
                    "type" : "hanlp",
                    "enable_stop_dictionary" : true
                }
            }
        }
    }
}
```
**验证效果**
```
GET test/_analyze
{
  "text": "美国,|=阿拉斯加州发生8.0级地震",
  "analyzer": "my_hanlp_analyzer"
}
```
```
{
  "tokens": [
    {
      "token": "美国",
      "start_offset": 0,
      "end_offset": 2,
      "type": "nsf",
      "position": 0
    },
    {
      "token": "阿拉斯加州",
      "start_offset": 0,
      "end_offset": 5,
      "type": "nsf",
      "position": 1
    },
    {
      "token": "发生",
      "start_offset": 0,
      "end_offset": 2,
      "type": "v",
      "position": 2
    },
    {
      "token": "地震",
      "start_offset": 0,
      "end_offset": 2,
      "type": "n",
      "position": 3
    }
  ]
}
```

**Comment by zhj12388** [comment]
我添加同义词了，type指定了custum，如果再指定hanlp，同义词会失效，如何同时配置停用词？

{
  "analysis": {
    "filter": {
      "my_synonym_filter": {
        "type": "synonym",
        "synonyms_path": "Sysnonym.txt"
      }
    },
    "analyzer": {
      "my_hanlp": {
        "type": "custom",
        "filter":["my_synonym_filter"],
        "tokenizer": "hanlp",
        "enable_stop_dictionary" : true
      },
      "my_hanlp_index": {
        "type": "custom",
        "filter":["my_synonym_filter"],
        "tokenizer": "hanlp_index"
      }
    }
  }
}

**Comment by zhj12388** [comment]
这种配置停用词不起作用
