### ISSUE TITLE
插件怎么打成zip包呀

### ISSUE THREAD

**Issue by lyg888** [KennFalcon/elasticsearch-analysis-hanlp#97]
源码怎么打包成hanlp-1.7.8-release.zip 这样子的 zip 包

**Comment by aboutZZ** [comment]
`gradle -x test build`
zip file:  `PROJECT_DIR/build/distributions`

**Comment by alieismy** [comment]
> 源码怎么打包成hanlp-1.7.8-release.zip 这样子的 zip 包

如果是maven，直接根目录下mvn clean package

**Comment by KennFalcon** [comment]
./gradlew assemble即可
